#!/bin/sh
# -----------------------------------------------------------------------------
# Entrypoint for the WebUI container.
#
# - Generates ~/.bitcoin/bitcoin.conf from BITCOIND_* env vars, so that
#   `bitcoin-cli` inside the sandbox reads the same credentials the Python
#   backend uses (single source of truth: .env).
# - Starts uvicorn with proxy-headers enabled so logs show real client IPs.
# -----------------------------------------------------------------------------

set -eu

BITCOIN_DIR="${HOME:-/home/sandbox}/.bitcoin"
mkdir -p "$BITCOIN_DIR"

# Write the config. Fallbacks match the defaults in the Python backend.
cat > "$BITCOIN_DIR/bitcoin.conf" <<EOF
# Auto-generated on container start by infra/entrypoint.sh from .env
# Do not edit this file directly: change the .env at the project root instead.

regtest=1

[regtest]
rpcconnect=${BITCOIND_HOST:-bitcoind}
rpcport=${BITCOIND_PORT:-18443}
rpcuser=${BITCOIND_USER:-bitcoin}
rpcpassword=${BITCOIND_PASS:-bitcoin}
EOF
chmod 600 "$BITCOIN_DIR/bitcoin.conf"

exec uvicorn app:app \
    --host 0.0.0.0 \
    --port 8080 \
    --app-dir /app \
    --proxy-headers \
    --forwarded-allow-ips='*'
